---
title: "ProteinPrediction1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Final Presentation

```{r}
library(ggplot2)
library(data.table)
setwd('/Users/paulhager/Documents/Uni/ProteinPrediction1/ProteinPrediction1/')
```

Epochs versus MCC

```{r}
epochMCCRaw <- read.csv('epochMCC_oldParams.csv')
epochMCCDT <- as.data.table(epochMCCRaw)
epochMCCDT

sp <- ggplot(epochMCCDT, aes(x=Epoch)) + geom_smooth(aes(y=MCC_TEST, colour = "MCC"), show.legend = FALSE) 
sp
# We could label where our grid search returns the best results with a vline, but it may be easier to just explain without
#sp + geom_vline(xintercept=380)

# We cen also include how the cutoff changed
sp2 <- ggplot(epochMCCDT, aes(x=Epoch)) + geom_smooth(aes(y=MCC_TRAIN, colour = "Cutoff"))
sp2

both <- ggplot(epochMCCDT, aes(x=Epoch)) + geom_smooth(aes(y=MCC_TRAIN, colour = "Train"), show.legend = FALSE) + geom_smooth(aes(y=MCC_TEST, colour = "Test")) + labs(y="MCC") + theme(legend.justification = c(0.05,0.95), legend.position = c(0.05,0.95))
both
```

Grid Search

```{r}
library(gridExtra)
library(dplyr) 
paramGridSearchRaw <- read.csv('allParameters.csv')
paramGridSearchDT <- as.data.table(paramGridSearchRaw)
paramGridSearchDT
base <- ggplot(paramGridSearchDT, aes(y=MCC))
batchSize <- base + geom_point(aes(x=BatchSize)) + geom_smooth(aes(x=BatchSize),method="lm")
hiddenNodes <- base + geom_point(aes(x=HiddenNodes)) + geom_smooth(aes(x=HiddenNodes),method="lm")
weightNonBinding <- base + geom_point(aes(x=WeightNonbinding)) + geom_smooth(aes(x=WeightNonbinding),method="lm")
weightBinding <- base + geom_point(aes(x=WeightBinding)) + geom_smooth(aes(x=WeightBinding), method="lm")
learningRate <- base + geom_point(aes(x=LearningRate)) + geom_smooth(aes(x=LearningRate), method="lm")
epochs <- base + geom_point(aes(x=Epochs)) + geom_smooth(aes(x=Epochs), method="lm")
momentum <- base + geom_point(aes(x=Momentum)) + geom_smooth(aes(x=Momentum), method="lm")
cutoff <- base + geom_point(aes(x=BestCutoff)) + geom_smooth(aes(x=BestCutoff), method="lm")

batchSize
hiddenNodes
weightNonBinding
weightBinding
learningRate
epochs
momentum
cutoff
grid.arrange(batchSize, hiddenNodes, weightNonBinding, weightBinding, learningRate, epochs, momentum, cutoff)

mccHist <- ggplot(paramGridSearchDT, aes(MCC)) + geom_histogram(color="darkblue", fill="lightblue") + labs(title="Hyperparameter Gridsearch MCC Histogram", y="Count") + theme(plot.title = element_text(hjust = 0.5))
```